### ISSUE TITLE
De active_menu is niet zichtbaar en tag zit niet op alle hoofdmenu items

### ISSUE THREAD

**Issue by Tijnoz** [Inter-Actief/amelie#114]
'active_menu' zit niet op alle menu items.
Normaal wordt het actieve menu item aangegeven, maar dit is niet overal zo.

**Comment by AVeenstra** [comment]
Even if it is set no visible effect can be observed, so --> front-end and editing the title

**Comment by J3173** [comment]
Maybe the conclusion is `active_menu` isn't used any more (at least in the main menu) and can be deleted?

**Comment by AVeenstra** [comment]
But I liked the feature :( @nickschot would you like to css the s*** out of this issue? Or is this feature knowingly pulled?

**Comment by SebastiaandenBoer** [comment]
The problem is that when a page is selected that does not share any kind of url substring, the menu indicator does not change (I tried this last week). Sadly, without refactoring many urls or finding another way of dealing with the selection, the indicator won't work. Therefore, we could either:
1) change urls to have module prefixes (even the about pages)
2) change the method used to select the main list parent based on the substring to where it would also include certain about pages (not fancy, but it could work)
3) remove the implementation all-together until we implement a proper bootstrap menu
