### ISSUE TITLE
Cannot remove people from committee in the committee editing fields when end date is current date

### ISSUE THREAD

**Issue by kimberlyh** [Inter-Actief/amelie#164]
Tried to remove one from the axi on different days. Filled in the end date (current date) when editing from the committee page and saved. Page reloaded and showed the end date. Then I checked the committee page again and they were still there (but the end date was empty again in the editing fields). When I entered yesterday's date, it went fine.

**Comment by Kurocon** [comment]
That's because our member administration only checks members when they are saved. Because you set the end date to "today", the member is not removed when they are checked because "today" is not smaller than the current day. The member will then be removed the next time they are checked. This does not happen automatically.
