### ISSUE TITLE
All browser caches should be cleared with every site update

### ISSUE THREAD

**Issue by jeffreybakker** [Inter-Actief/amelie#215]

**Comment by windwarrior** [comment]
In theory, all our JS/CSS should be bundled, compressed and have a unique filename thanks to django-compressor. Looking at the live site, this appears to not work...

**Comment by jeffreybakker** [comment]
It does work, but the web browser has local caches, and those should be cleared automatically. Right now you can clear them with SHIFT + F5

**Comment by windwarrior** [comment]
Yeah, but we can't tell a computer to clear its caches. We can at most force it to break its caches by tricking it to believe the CSS/JS/Static files changed. 

A common technique is having a sort of version in your css/js filenames, which django-compressor does by default. However, _that_ feature doesn't seem to work right now.

So, for our little website the css would then be called
```
/static/cache/amelie.3842942.compressed.js
```

**Comment by windwarrior** [comment]
Interestingly, the website instructs no js/css to be cached without querying the server whether this is the newest version. All cache headers seem to say `Cache-Control: no-cache`.

**Comment by Kurocon** [comment]
This seems to be a problem in the compile_css.sh script that generates the compiled.css for production. I don't know how our JS is compressed, but that at least could explain the CSS caching issue. The only problem is how do we generate a proper "timestamp" in compressed files *and* also removing any older versions of it when compiling.

**Comment by MMeent** [comment]
use a hash (crc32 or md5 should be fine already) as the filename, which is also saved in the settings

**Comment by windwarrior** [comment]
Yeah, you want to use hashes for cachability. I think we might be able to remove `compile_css.sh` in its entirity because django-compressor has builtin support for preprocessing less-files (Same goes for babel! or typescript! or flow!). Look for example at [this django-compressor setting](https://django-compressor.readthedocs.io/en/latest/settings/#django.conf.settings.COMPRESS_PRECOMPILERS).

**Comment by Kurocon** [comment]
That would be nice to investigate, I can't count the amount of times I forgot to compile CSS and was wondering why some style-related thing wasn't working on live :P

**Comment by AVeenstra** [comment]
It is quite easy to force computers to clear their caches:
https://bitbucket.org/ad3w/django-sstatic/src/4401a4bc3058618dfc2eafaee6a23d287a99ede5/sstatic/templatetags/sstatic.py?at=default&fileviewer=file-view-default

It adds a timestamp to the file url which the server ignores, but since the timestamp changes after an update the url changes too. Another url means that the computer will download the new file.

If the compressor works it would be more awesome, but this is an easy to implement 'hack'.

**Comment by windwarrior** [comment]
caching = good.

I am a strong opponent of any technique that makes legitimate caching non-functional, we only need to find a way to convince the browsers cache that its cached copy is no longer valid.

**Comment by Kurocon** [comment]
Agreed, let's just get compressor working and it'll be fine :)

**Comment by AVeenstra** [comment]
The browser will use it's cache as long as the entire url is equal. So only if the url changes (which happens when the timestamp of the file changes (which happens after every site update)) will the browser stop using the previously cached file.

I think using the compressor is best, but if it does not work my proposed solution will solve the caching problem.

**Comment by windwarrior** [comment]
Oh right, I thought you wanted to append the current time, which would mean no version would ever be cached...

**Comment by Sophietje** [comment]
Ping @AVeenstra fix?

**Comment by SebastiaandenBoer** [comment]
Well, we can always check the tile changed time...
