### ISSUE TITLE
An event with only an English description does not display that description when the site / app is in Dutch

### ISSUE THREAD

**Issue by Quitlox** [Inter-Actief/amelie#222]
See the IntegraCee Wine Tasting event. It only has an English description but it is not displayed on the dutch version of the website.

This is also the case for the API, which then only shows the (empty) dutch description

**Comment by windwarrior** [comment]
That makes sense right? A summary is optional, and since the website either shows everything dutch or shows everything english, it shows the dutch summary on the (also) dutch site.

I would suggest this is an content issue, other activities (that are only dutch) have resorted to storing in the english field that only a dutch description is available or the other way around.

I dont think we want a mixed-language website, do we?

**Comment by Kurocon** [comment]
I agree with @windwarrior, this is intended behaviour. Committees need to enter both a dutch and english description if they want their events promoted in both languages. In exception cases it might be acceptable to put an english description in the dutch field, but I think that would only be ok after discussion with the board.

**Comment by SebastiaandenBoer** [comment]
I agree with the comments made above, however I would like to point out that when *only* adding a description in Dutch, a notification is shown that an English description is missing. A warning for missing Dutch descriptions would be worth implementing in my opinion.

**Comment by 11gamer11** [comment]
We will add a warning when there is no Dutch translation.
