### ISSUE TITLE
Add English functions

### ISSUE THREAD

**Issue by dennis-cai** [Inter-Actief/amelie#250]
At the moment it is not possible to provide a bilinugal function description for active members. You can only add a Dutch or an English description. It would be nice if a bilingual option could be added.

**Comment by Sophietje** [comment]
Dear Dennis,
This ticket has already been closed #152. This is because we consider the study association to be English and therefore we expect the board to only use English function names. Moreover, making the fields bilingual would require a lot of models to be modified. It would also mean that all current functions needs to be translated by the board, which is a huge amount of work.
We hope to have informed you sufficiently.
Kind regards,
Sophie
