### ISSUE TITLE
Description of "priority" boolean in News article is wonky

### ISSUE THREAD

**Issue by dennis-cai** [Inter-Actief/amelie#259]
Currently the ordering of the news posts on the IA website is broken. See screenshot.

**Comment by dennis-cai** [comment]
![stucie website faal.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58c2b48ddafee51a00cf18d3/125516c66e82c728ace21e0d46fb808f208b86e998ecbd50ad49f5d42f47267f6b48e13b628ae92dbc56395b4d5a49a941590e41faaf8d78aee568258c5c0befd86b0c74932f0dbefad341eb5ee779c11ac7a4b6984fc2e23c21ee8c86483f18011080f85527ed.PNG)

**Comment by windwarrior** [comment]
I've taken the liberty of changing your title, because it is not actually a bug.

The "nieuwe studiereiscommissie" news article was flagged as having priority. This prio feature was added because sometimes important news articles ("looking for board") would get flooded off the front page by other news articles.

I have removed this "priority" flag from the news article and now it is chronological again. I will keep the ticket open because of the terrible description of the feature. I would suggest the following:

- [ ] Replace the fields name to "pinned", to be in line with the Facebooks and the Twitters
- [ ] Update the description to indicate that checking the box would "pin" the post
- [ ] (Maybe?) Indicate on the FP that a post is "pinned" and thats why the order is off
