### ISSUE TITLE
Enrollment option for external activities

### ISSUE THREAD

**Issue by Floormidabel** [Inter-Actief/amelie#321]
Companies sometimes indicate they want to know how many people are going to join an external activity. Having the possibility to sign up for external activities would be useful for this. Example; the procam pinkroccade inhouseday is officially an external activity but they needed to know how many people would come because of the bus they would order.

**Comment by SebastiaandenBoer** [comment]
Although I completely agree with this issue, I just wanted to come in and note that such a change will have a substantial effect on the API. Just saying ;)

**Comment by windwarrior** [comment]
I think its also pretty challenging to engineer because enrollment is captured in the `Activity` model which extends the `Event` model. The `BedrijfEvent` extends `Event`, so doesn't have any enrollment information presently.

It may require some more substantial reengineering to implement correctly.
