### ISSUE TITLE
Make it possible to enroll other people through Amelie-API by committee

### ISSUE THREAD

**Issue by Yoeori** [Inter-Actief/amelie#322]
As of now it is not possible to use the `activitySignup` API endpoint to enroll someone other than yourself. This makes it practically impossible to manually sign up someone if an activity is controlled by an external application (like SymposIA).

**Comment by SebastiaandenBoer** [comment]
This is by design. Someone should always explicitly indicate that they want to enroll for an activity. To make use of the API properly, one should authenticate with it first. Then use the OAuth2 token of that person to register for the activity.

An external application should NEVER be able to enroll someone without explicit interaction.

**Comment by Yoeori** [comment]
I meant to imply that an authorized committee member is enrolling someone (so still authorized by OAuth), on the site it is possible for committee members to enroll people for their events, this is not possible if the event is managed by an external application, this should be possible.

**Comment by SebastiaandenBoer** [comment]
We have decided still not to fix this as there are issues with regards to data-policy. You would have to identify a user without its token (as otherwise you could just enroll the user yourself with this token), which is not desired as it would expose certain sensitive personal information.

The implementation of a reserve-list (#12) for activities can solve this issue in most use-cases, though this is currently not being worked on.
