### ISSUE TITLE
OAuth login Wiki keeps asking for permission

### ISSUE THREAD

**Issue by WKobes** [Inter-Actief/amelie#325]
Every time you logon the IA website, the wiki also requests new permissions. This results in a long list of permissions (see image).
![image](https://user-images.githubusercontent.com/9413731/38797602-491e016c-415f-11e8-9abe-802fc565eb6d.png)

**Comment by Kurocon** [comment]
Yes, when we moved the wiki over to use the website as a login source with oAuth, I saw this problem too, but hoped it would not be this bad. The main issue is that the wiki needs to get a new authorization every time you login because the wiki does not keep track of the oAuth refresh tokens when you are logged out (or automatically logged out due to inactivity). This is a limitation in the oAuth plugin we use.

While I was working on a solution, I came across OpenID Connect, which is a layer on top of oAuth to provide a standardized way to exchange basic profile information. If we can support this protocol in Amelie, we don't need to customize the wiki's auth plugin to get the user's data (name/username) out of the website, but we can use a pre-built MediaWiki plugin [1].

Unfortunately, django-oauth-toolkit does not support OpenID Connect (yet). There is another oAuth library for Django which does (django-oidc-provider) [2], but this also provides an oAuth provider, so we need to remove django-oauth-toolkit and switching might be a bit of a hassle. I also found that a PR is in the works to add OpenID Connect support to django-oauth-toolkit [3], which has been updated recently and is waiting for the 3.0.0 release of its upstream library (oauthlib) [4]. So, we could also wait for that, but we have to live with the excessive tokens until then.

So, summarizing; to properly support this in Amelie, there are two options:
1. Switch to django-oidc-provider which already includes OpenID Connect support.
2. Wait for the PR in django-oauth-toolkit (and the release of oauthlib 3.0.0) and switch to it then.

I think option 2 is the best for us, as it requires minimal code modifications in Amelie, and seeing that the current system 'works' well enough, and that both the PR and the Oauthlib release are almost done, we should not have to wait too long for it. I've subscribed myself to notifications on both, so I'll know when they get merged.

[1] https://www.mediawiki.org/wiki/Extension:OpenID_Connect
[2] https://github.com/juanifioren/django-oidc-provider
[3] https://github.com/jazzband/django-oauth-toolkit/pull/545
[4] https://github.com/oauthlib/oauthlib/issues/512

**Comment by WKobes** [comment]
@Kurocon please check if all blocking issues are resolved.

**Comment by Kurocon** [comment]
Django-oauth-toolkit has had a release back in March with OIDC support, so we can finally start working on this.

This does however need help from the system administrators, as a new plugin has to be installed in the Mediawiki

**Comment by Kurocon** [comment]
This has become outdated with the move to the new authentication platform
