### ISSUE TITLE
Publications should be opt-in

### ISSUE THREAD

**Issue by SebastiaandenBoer** [Inter-Actief/amelie#331]
Publications should be opt-in and provide a method for opt-out on the profile page. This change should also be reflected on the member edit page accessible by the board, which currently states that this should only be changed in extreme situations.

**Comment by Kurocon** [comment]
This needs to be changed in the enrollment form and possibly in the member profile preference form. The default needs to be set to false, but it might be nice to add a message to encourage people to tick the box. Not only because we get money from sponsors for it, but also because the IO-vivat is a nice publication to get.

**Comment by SebastiaandenBoer** [comment]
"gratis"/"free" should be incentive enough

**Comment by Kurocon** [comment]
Fixed by changing the corresponding Preference object in production.
