### ISSUE TITLE
Check our code and settings for private data

### ISSUE THREAD

**Issue by Kurocon** [Inter-Actief/amelie#340]
Need to go through code to see whether there are no passwords, personal information, etc. hardcoded. (deadline: end of July)

**Comment by Sophietje** [comment]
So I finally managed to go through the complete up-to-date code. I found the following things for which we should consider whether they need to be removed or not (I first mention the file then -> followed by what information I found):

- [ ] amelie/activiteiten/management/commands/checkreserveringen.py -> bestuur @inter-actief.net, links to SU, 
- [ ] amelie/activiteiten/activity_enrollment.html -> board @inter-actief.net
- [ ] amelie/activiteiten/mail.py -> bestuur @inter-actief.net
- [ ] amelie/bedrijven/management/commands/bannercheck.py -> www @inter-actief.net, samenwerking @inter-actief.net
- [ ] amelie/claudia/templates/accounts/password_reset.mail -> accountbeheer @inter-actief.utwente.nl
- [ ] amelie/claudia/templates/claudia/account_created.mail -> http:// intra.ia.utwente.nl, accountbeheer @inter-actief.utwente.nl, wiki.ia.utwente.nl, inter-actief.utwente.nl/account/activate
- [ ] amelie/claudia/account_deleted.mail -> accountbeheer @inter-actief.utwente.nl
- [ ] amelie/claudia/ad.py -> profilepath, unixhomedir
- [ ] amelie/claudia/tools.py -> mail domains
- [ ] amelie/data_export/templates/data_export/mails/export_complete.mail -> board @inter-actief.net
- [ ] amelie/data_export/templates/data_export/metadata/metadata.txt -> www @inter-actief.net
- [ ] amelie/data_export/tasks.py -> www @inter-actief.net
- [ ] amelie/iamailer/templates/iamailer/email_basic.mail -> contact @inter-actief.net, 
- [ ] amelie/leden/management/commands/birthday_mail.py -> board email address
- [ ] amelie/leden/management/commands/customquery.py -> This is not private info but it seems like this can be removed
- [ ] amelie/leden/management/commands/dataupdatemail.py -> board email address
- [ ] amelie/leden/management/commands/yeartransfer.py -> secretaris @inter-actief.net
- [ ] amelie/leden/members/yeartransfer_ended.mail -> contains link to eniac website
- [ ] amelie/leden/committee_map.html -> Seems to contain some kind of javascript api key in a link to google
- [ ] amelie/leden/committees.html -> Link to committee booklet on media.ia.utwente.nl
- [ ] amelie/leden/forms.py -> secretary @inter-actief.net email address, IBAN NL18ABNA0484869868
- [ ] amelie/leden/templates/committee_map.html -> seems to contain an api key in link?
- [ ] amelie/settings/generic.py -> IBAN, links naar hex, radius1, SECRET KEY, service account p12 file?, more email addresses, Microsoft Imagine account number, 
- [ ] amelie/settings/travis.py -> SECRET_KEY
- [ ] amelie/streeplijst/export/sepadd.xml -> Contains IBANs and BICs
- [ ] amelie/streeplijst/debt_collection.py -> IA telephone number
- [ ] amelie/streeplijst/views.py -> Contains the phone number of IA 0534893765, mail address for penningmeester (penningmeester @inter-actief.net), Incassant-ID: NL81ZZZZ400749470000
- [ ] amelie/tools/management/commands/www_obfuscate.py -> www email address
- [ ] amelie/tools/saml_processors.py -> You can find the standard e-mailaddress for ALL active members here since it explains the standard format "Firstname.lastname @inter-actief.nl", note however that you can also find this info in the code, so removing this does not seem useful
- [ ] pullmaster.sh -> Martijn Hoogesteger's (inter-actief) email, Kevin's (inter-actief) email
- [ ] amelie/test_all_urls.py -> # TODOs to remove things about the old oauth (oauth2)
- [ ] amelie/weekmail/templates/weekmail/weekmail_mail_plain.mail -> fax number seems no longer necessary?
- [ ] amelie/weekmail/templates/weekmail/weekmail_mail_html.mail -> Footer refers to website with http instead of https
- [ ] amelie/weekmail/static -> remove unused icons

Side-note 1: Perhaps remove the Jelte module? (it is not translated)
Side-note 2: And perhaps we can also remove the SMS functionality?
Side-note 3: claudia/google.py -> Uses SHA-1 as hash function which is no longer considered secure

**Comment by SebastiaandenBoer** [comment]
As a comment on your side-note. The SMS functionality should now be removed after the recent push-notification refactor.
