### ISSUE TITLE
Candidate Board rights for the Room Duty tool

### ISSUE THREAD

**Issue by jeffreybakker** [Inter-Actief/amelie#353]
As of right now we, the candidate board, don't have the full rights for the room duty tool. I'd like to be able to create new weeks and print them so that I won't have to rely on Jotte doing those all the time

**Comment by niomaster** [comment]
We can easily add this, however we do not filter on the candidate board for permissions anywhere else in the website. I believe in most cases we assume that the board gives the candidate board "board rights" on the website at some point, after which this is not an issue. Do we think that it is worth it to make an exception in this case, and grant the candidate board rights for the room duty always?

**Comment by niomaster** [comment]
I guess btw that we can drop the `require_bestuur` from `schema_print`, since the assignees are semi-public information anway.

**Comment by WKobes** [comment]
That last thing is true. As for the other stuff, difficult. I think there is enough time after the board weekend (after which the candidates get full access) to work with these features. Before that, the board is responsible and will have to do the mentioned tasks.

**Comment by Kurocon** [comment]
I'm closing this as wontfix due to the reasons specified earlier:
- Board can create weeks/etc and add CB to the tool to fill in their availability
- There are a lot of other features of the website also limited in the same way (board only until the CB gets rights) 
- CB gets privileges on the website at some point anyway

I have created a new ticket (#394) for the schema_print rights.
