### ISSUE TITLE
Leden toevoegen aan commissies

### ISSUE THREAD

**Issue by Sophietje** [Inter-Actief/amelie#39]
Dit klinkt natuurlijk heel overduidelijk maar de huidige workflow is andersom.

Huidig:

```
Maak een commissie
Ga naar leden
Zoek je lid dat je toe wil voegen
Voeg in een multiformsetellendeapparaat het lid toe
Goto 3 voor alle andere leden 
```

Maar eigenlijk is dit onlogisch. Logischer is om een persoon toe te voegen aan een commissie.

---

Om dit te fixen kun je kijken hoe het nu gaat, er is een FunctieForm? en een persoon_functies functie in amelie.

Check:

```
leden/forms.py (zo rond line 396)
leden/ajax_views.py (zo rond line 230)
```

**Comment by J3173** [comment]
Misschien een vergelijkbaar FunctieForm toevoegen op de commissiepagina? Is wel lastig, want het zoeken op leden binnen een formulier is moeilijk goed te doen omdat we er zo'n duizend hebben.

**Comment by AVeenstra** [comment]
Proof of concept can be found on the branch [fix_ia_amelie#39](/Inter-Actief/amelie-private/tree/fix_ia_amelie%2339). A new link has been added: /commissies/151/appcie/leden/ (any other committee should work too). It works like the FunctieForm, but instead of a drop down for committee selection it has a autocompleting member search field. This field could also be used instead of the search field used to enrol people to activities.

Any suggestions on how to proceed would be welcome as the page is quite ugly and is quite big with some committees.
How many entries should I show?
Should I add a delete button?
Should I prevent a change to the function name?

**Comment by J3173** [comment]
I think big and ugly aren't big problems, because it is only a page for the board to use, and only some committees have a large history.

I would not try to limit the number of existing entries, I guess this can be quite hard in Django and not that useful. I would show about ten empty entries since most new committees have at most ten members.

I would not add a delete button as the similar form on /leden also doesn't have a delete button. The general rule is not to delete entries to keep the committee history. Erroneous entries can be deleted by WWW superusers.

Preventing changing function names (or other existing information) is an option, but as far as I know it isn't an existing feature in Django. It also disallows valid modifications, like fixing typos. I think you shouldn't do this.
