### ISSUE TITLE
User of Person not updated correctly

### ISSUE THREAD

**Issue by niomaster** [Inter-Actief/amelie#495]
When you log in via UT, a `User` is always created. When the s-number or m-number matches a `Person` and the person has no bound account, we try to bind it or create it instead. However, when a student becomes an employee, the bind already exists, so the user of `Person` is not updated, see  [here](https://github.com/Inter-Actief/amelie-private/blob/38097b170274b93591019406fa4ac9df228c4dbc/amelie/members/models.py#L320). Probably, we just need to check whether the passed username (the true login name) matches the bound `User`.

**Comment by Kurocon** [comment]
Is there any case where having the incorrect username stored in the `User` model is causing issues? Because if we check the username in the `get_or_create_user` function, then this will also update the user when someone logs in using their IA-account (`get_or_create_user` is also used in the [IALoginBackend](https://github.com/Inter-Actief/amelie-private/blob/38097b170274b93591019406fa4ac9df228c4dbc/amelie/tools/auth.py#L54)). So, this already was a 'problem' if someone has a student account and an Inter-Actief account and uses both.

If this desync causes problems somewhere, then we need to devise some kind of solution for only s- and m-accounts, or find a way to link multiple sign-in names to a single user (maybe take some inspiration from Alexia, which [already supports that](https://github.com/Inter-Actief/alexia/blob/master/alexia/auth/backends.py#L14))

**Comment by niomaster** [comment]
Had to think about what happened a bit again :D. The process is:

* Student becomes member and logs in with s-account
* Student becomes employee; this is correctly reflected in `employee__number`
* Employee logs in the website

We now have:
* `Person(id=1, no=m12345)`
* `User(id=1, uname=s54321)`
* `User(id=2, uname=m12345)`

where person#1.user == user#1. When you log in with m12345, the request user is set to user#2. On initial login person#1 is fetched by login name, `get_or_create_user(m12345)` is called on person#1. Since person#1 has a valid user it is not created or updated. Later the person middleware tries to fetch the person of the request user, user#2, but since person#1 was not updated, user#2 is not associated with a person, leading to "Hello, you are unknown in our administration" etc.

I don't think we need a multi-UT-login solution necessarily, I think it's fine to just force a user update if the user does not match (i.e. `matched_person.user != request.user` in the SAML backend ==> set the user). I think the only bad effect that could have is that an employee can't use their s-account anymore to log in (don't think that's a problem).

**Comment by niomaster** [comment]
The difference with the `IALoginBackend` is that it returns a user, I guess that necessarily overrides the user.

**Comment by Kurocon** [comment]
Ah, I see the problem now. Should be pretty easy to fix.

**Comment by Kurocon** [comment]
@niomaster I think I've found an acceptable fix/workaround for the problem, which handles it in the same way that the old RADIUS logins handled this problem, and which the IALoginBackend still does. Do you agree?

**Comment by niomaster** [comment]
Yes, let's keep it consistent with the IALoginBackend
