### ISSUE TITLE
Check if IBAN is from a SEPA country at enrollment

### ISSUE THREAD

**Issue by WJ44** [Inter-Actief/amelie#563]
Mandates for payment are only supported for SEPA countries. It would be nice if the website would only let you fill in valid SEPA BICs or IBANs.

**Comment by WJ44** [comment]
I do not know the way in whcih the current implementation is happening, but it would be a very nice bonus if it would be validated that the BIC indeed belongs with the IBAN. Another very nice bonus, but I do not know if it is possible, It seems to me (not 100% sure) that some banks participating in SEPA do not support SEPA mandates. If there is some way to validate this that would be great (might not be relevant anymore with eMandates).

**Comment by WJ44** [comment]
While needing to find the BIC of some bank I came accross this website which indeed shows whether a certain IBAN supports SEPA direct debits, so if this was not already considered with the implementation, it is definitely possible and would be great. https://www.ibancalculator.com/

**Comment by pietervanheijningen** [comment]
> While needing to find the BIC of some bank I came accross this website which indeed shows whether a certain IBAN supports SEPA direct debits, so if this was not already considered with the implementation, it is definitely possible and would be great. https://www.ibancalculator.com/

Good point on mentioning it, because you mentioned that I found a library that can just convert IBAN's to BIC's according to the ISO standard: https://github.com/mdomke/schwifty So we'll just use that, and then the user won't even have to enter their BIC number. I'll be sure to still keep in the code in that checks If its from a SEPA country though.
