### ISSUE TITLE
Link to intra.ia.utwente.nl under the `members' dropdown

### ISSUE THREAD

**Issue by zwouter** [Inter-Actief/amelie#586]
Pretty much like the title says, it could be nice if the link to the intranet could be put somewhere on the website.

https://intra.ia.utwente.nl

**Comment by WKobes** [comment]
Seems to me like this is only useful for active members, right? We could add it only for active members.

Also: there are quite some dead links on there, maybe we should update it first.

**Comment by zwouter** [comment]
I've just also sent an email to the SysCom listing everything that's outdated on there. So that's being worked on.

And yes, adding it only for active members could be smart if that's possible.

**Comment by CazSaa** [comment]
Since none of the links in the navbar are restricted to active members, I think it is fine to keep this link unrestricted too. This also makes it easier to access when you're not logged in.

**Comment by WKobes** [comment]
> Since none of the links in the navbar are restricted to active members, I think it is fine to keep this link unrestricted too. This also makes it easier to access when you're not logged in.

I do not agree, all of those entries are clearly focused on all member (~1200 people), maybe except for corporate identity which still would sometimes be handy for average members. The intra site, however, is clearly focused on active members only (~150 people), except for the link to the summary wiki which is also on the main website.

Especially links like the year planning and promotion planning are not supposed to be open to everyone, since they would be able to trash it. It think you should reconsider this

**Comment by CazSaa** [comment]
Which links, other than the year and promotion planning, do you think are focused on active members only? I think the majority of links in Intraweb are useful for all members: PC/website issues, books, (summary) wiki, drink planning, and all the committee websites for example. I am not sure what all the links under 'Internal' are for but all of them are password protected so I don't see any harm in exposing the links like this. 

As for the year and promotion planning, I agree they're focused on active members but not putting them on the website for non-active members still does not prevent anyone from being able to trash the sheets since they're made public anyway.

I think the pro of being able to quickly access the link without having to be logged in outweighs the fact that people get a link to two spreadsheets which are already public regardless of whether we put a link to the Intraweb in the dropdown. Let me know what you think :)

**Comment by WKobes** [comment]
In response:

- The website issues have a button in the footer on all pages
- The summary wiki has his own entry in the education navbar
- The books has his own entry in the education navbar
- drink planning/Alexia is only administrative and does not represent activities. Regular users will only use the activities on our website. Alexia is not aimed at the average member.
- Committee websites posted there are mostly archived/for activities that have already taken place. Ongoing committees will promote their own website on the IA site anyways

Thus all except 'PC issues' are already easily found through the main website.

That the two schedules are already public now does not mean that the link is known to everyone. Just like not everyone will read this discussion. I think it is a bad idea to expose the links in this manner, especially if the intra environment provides little to none new content for average members

**Comment by Kurocon** [comment]
I agree with Wouter here, the intraweb is aimed at active members (and the internal section even mostly at the WWW and SysCom committees). There is no significant benifit to having this publicly in the main navigation of our website.

**Comment by CazSaa** [comment]
> * The website issues have a button in the footer on all pages
> * The summary wiki has his own entry in the education navbar
> * The books has his own entry in the education navbar

I wasn't aware those existed, my bad. 

Thanks for your explanation! I'll change it so that the link is only visible for active members.
