### ISSUE TITLE
Payment status cash payments

### ISSUE THREAD

**Issue by WJ44** [Inter-Actief/amelie#593]
It would be nice to have the ability to track the payment status of cash payments for activities just like for the contribution. Perhaps it would be possible to have a checkbox in the overview of enrollments.

**Comment by WKobes** [comment]
In the current implementation, enrolling someone with a cash payment can only be done by the board and payment should be done at the moment of enrollment. The way we register payments for membership is completely different from activities, thus this should not be compared.

I wonder whether there are many situations where the board enrols someone using cash, but do not receive an immediate payment? Moreover, I doubt we should add more support for cash payments since we want to promote using our direct debit system.

**Comment by bramvandartel** [comment]
> I wonder whether there are many situations where the board enrols someone using cash, but do not receive an immediate payment?

Most of the requests for enrolments via cash are done by email. Currently, the board has an Excel-sheet for the registration of payments, so there would be a use case when this is implemented.
