### ISSUE TITLE
See number of enrolled people for an activity

### ISSUE THREAD

**Issue by Michael-Janssen-dev** [Inter-Actief/amelie#595]
At the moment, it is not possible to see how many people are enrolled for an activity(as a normal member). It might be a nice addition to add this, if you're logged in.

**Comment by WKobes** [comment]
My two cents: the board should think about whether they want this feature. People will use the number in their considerations to enrol for an activity. I expect smaller activities to receive even fewer enrollments due to this. At the same time, I do not see major benefits for members in being able to see this number.

**Comment by SimplyPancake** [comment]
For activities with a sign-up limit; it would be nice to show:
_X/Y signed up_ where X is the amount of people that have signed up, and Y is the limit

Without a limit; it could just show
_X people signed up_
