### ISSUE TITLE
Allow access for Audit to /company/statistics

### ISSUE THREAD

**Issue by WikiRik** [Inter-Actief/amelie#622]
In #487 an export was added for the Audit committee, but unfortunately the page /company/statistics is not available for the members of the Audit committee. While we can imagine that this is due to #54 it would be useful in this case to hardcore access for the Audit committee members so this can adequately be checked.

**Comment by Kurocon** [comment]
Ah yes, it seems that we intended to wait for #54 (comment in https://github.com/Inter-Actief/amelie-private/blob/master/amelie/companies/views.py#L316 ) but that turned out to take longer than expected.

In the mean time we've added specific page permissions a few times before already, so it should not be difficult at all to allow this for the Audit committee here as well.

**Comment by bramvandartel** [comment]
Fixed by @elisaado by Inter-Actief/amlie-private#565
