### ISSUE TITLE
Event better cancellation feedback

### ISSUE THREAD

**Issue by SimplyPancake** [Inter-Actief/amelie#696]
Right now, if an event is cancelled, there is written 'CANCELLED' in the event name, however this event still gets broadcasted in, for example, the room monitor (with the name "CANCELLED: ING WORKSHOP")! 
Maybe it would be nice to have an extra database field if an event is cancelled and to display a nice colour / label on the website and room monitor

**Comment by Mihai98924** [comment]
We can filter on the front-end as well. If the event contains the keyword `CANCELLED` we can hide it. If we do that, we do not need to change the table structure. What do you think @Kurocon ?

**Comment by SimplyPancake** [comment]
I do think that a better way of doing this is by altering the table structure! Then we don't have to reserve a word! Also I really like the idea that enrolled people get an email when an activity is cancelled

Met vriendelijke groet,
Daniel Jonker
________________________________

**Comment by supertom01** [comment]
I agree with Daniel. This will probably also be more clear in the future and it enforces it across all systems (boards, website, app and etc.)

**Comment by Kurocon** [comment]
Unfortunately we found some issues in testing in Staging:

The cancellation e-mails are being sent in the background thread via Celery, by which time the unenrollment of all participant has already occurred. So the participation data is not available any more.

The solution is to pre-generate the participation data instead of reading it from the models in the mail template, before deleting everything. Then when the mails are sent the context will still have the correct info.
