### ISSUE TITLE
Add reason to show underage participants of activity

### ISSUE THREAD

**Issue by P1mguin** [Inter-Actief/amelie#697]
Currently, showing underage participants at an activity requires no statement of reason. However, since you are using personal details it is likely that this is in fact required - considering that more often than not other personal details are shown based on this filter.

**Comment by WKobes** [comment]
I assume you mean adding a reason for usage similar to the reason for export? I personally think this filter should be restricted to board only (which do not require to enter a reason for viewing registrations, only export).

Active members have no regular access to birth dates other than those on the home page (opt in), thus granted them access to the filter gives more data than before. Since there are only few specific activities where this filter is used, active members should request a filtered export at the board.

**Comment by Nierot** [comment]
The board agrees with @WKobes here and I've made a pull request which changes this
